import type { EditableFieldKey } from '../domain/metadata';
import { parseSupportedUrl } from '../domain/youtube-url';
import { readCurrentTranscript } from '../content/readers/transcript';
import type { TranscriptReadOutcome } from '../content/readers/transcript';
import { isRecord } from '../domain/validation';
import { isErrorCode } from '../shared/errors';
import type {
  ClearSessionDataResponse,
  DraftMutationResponse,
  ExtractionResponse,
} from '../shared/messages';
import { PROTOCOL_VERSION } from '../shared/messages';

function isExtractionResponse(value: unknown): value is ExtractionResponse {
  if (!isRecord(value)) return false;
  if (value.ok === true) {
    const state = value.state;
    return (
      isRecord(state) &&
      isRecord(state.snapshot) &&
      typeof state.snapshot.videoId === 'string' &&
      isRecord(state.draft) &&
      typeof state.revision === 'number' &&
      typeof state.epoch === 'number'
    );
  }
  return value.ok === false && isErrorCode(value.code);
}

function isDraftMutationResponse(value: unknown): value is DraftMutationResponse {
  if (!isRecord(value)) return false;
  if (value.ok === true) return typeof value.revision === 'number';
  return value.ok === false && isErrorCode(value.code);
}

function isClearSessionDataResponse(value: unknown): value is ClearSessionDataResponse {
  if (!isRecord(value)) return false;
  if (value.ok === true) return true;
  return value.ok === false && isErrorCode(value.code);
}

async function sendMessage(message: unknown): Promise<unknown> {
  try {
    return await chrome.runtime.sendMessage(message);
  } catch {
    return { ok: false, code: 'INVALID_PAYLOAD' };
  }
}

export async function requestOpenVideo(
  tabId: number,
  sessionToken: string,
): Promise<ExtractionResponse> {
  const response = await sendMessage({
    type: 'OPEN_VIDEO',
    protocolVersion: PROTOCOL_VERSION,
    tabId,
    sessionToken,
  });
  return isExtractionResponse(response) ? response : { ok: false, code: 'INVALID_PAYLOAD' };
}

export async function requestRefreshVideo(
  tabId: number,
  videoId: string,
  sessionToken: string,
  epoch: number,
): Promise<ExtractionResponse> {
  const response = await sendMessage({
    type: 'REFRESH_VIDEO',
    protocolVersion: PROTOCOL_VERSION,
    tabId,
    videoId,
    sessionToken,
    epoch,
  });
  return isExtractionResponse(response) ? response : { ok: false, code: 'INVALID_PAYLOAD' };
}

export async function requestPatchDraft(input: {
  tabId: number;
  videoId: string;
  field: EditableFieldKey;
  value: string | string[];
  sessionToken: string;
  epoch: number;
  baseRevision: number;
}): Promise<DraftMutationResponse> {
  const response = await sendMessage({
    type: 'PATCH_DRAFT',
    protocolVersion: PROTOCOL_VERSION,
    ...input,
  });
  return isDraftMutationResponse(response) ? response : { ok: false, code: 'INVALID_PAYLOAD' };
}

export async function requestResetDraft(input: {
  tabId: number;
  videoId: string;
  fields?: EditableFieldKey[];
  sessionToken: string;
  epoch: number;
}): Promise<DraftMutationResponse> {
  const response = await sendMessage({
    type: 'RESET_DRAFT',
    protocolVersion: PROTOCOL_VERSION,
    ...input,
  });
  return isDraftMutationResponse(response) ? response : { ok: false, code: 'INVALID_PAYLOAD' };
}

export async function requestClearSessionData(
  sessionToken: string,
): Promise<ClearSessionDataResponse> {
  const response = await sendMessage({
    type: 'CLEAR_SESSION_DATA',
    protocolVersion: PROTOCOL_VERSION,
    sessionToken,
  });
  return isClearSessionDataResponse(response) ? response : { ok: false, code: 'INVALID_PAYLOAD' };
}

function isTranscriptOutcome(value: unknown, videoId: string): value is TranscriptReadOutcome {
  if (!isRecord(value)) return false;
  if (value.ok === false) {
    return ['VIDEO_CHANGED', 'NO_CAPTIONS', 'FETCH_FAILED', 'INVALID_RESPONSE', 'TOO_LARGE']
      .includes(String(value.reason));
  }
  if (value.ok !== true || value.videoId !== videoId) return false;
  if (!Array.isArray(value.tracks) || value.tracks.length > 40) return false;
  if (!value.tracks.every((track: unknown) => isRecord(track)
    && Number.isSafeInteger(track.index)
    && typeof track.languageCode === 'string'
    && track.languageCode.length <= 32
    && typeof track.label === 'string'
    && track.label.length <= 80
    && typeof track.autoGenerated === 'boolean')) return false;
  if (!Number.isSafeInteger(value.selectedIndex)
    || !value.tracks.some((track: { index: number }) => track.index === value.selectedIndex)) return false;
  if (!Array.isArray(value.segments) || value.segments.length > 20_000) return false;
  let totalCharacters = 0;
  for (const segment of value.segments) {
    if (!isRecord(segment) || !Number.isSafeInteger(segment.startMs)
      || (segment.startMs as number) < 0 || typeof segment.text !== 'string'
      || segment.text.length > 10_000) return false;
    totalCharacters += segment.text.length;
    if (totalCharacters > 1_000_000) return false;
  }
  return value.segments.length > 0;
}

export async function requestTranscript(
  tabId: number,
  videoId: string,
  trackIndex: number | null = null,
): Promise<TranscriptReadOutcome> {
  try {
    const tab = await chrome.tabs.get(tabId);
    if (!tab.url || parseSupportedUrl(tab.url)?.videoId !== videoId) {
      return { ok: false, reason: 'VIDEO_CHANGED' };
    }
    const results = await chrome.scripting.executeScript({
      target: { tabId, frameIds: [0] },
      world: 'MAIN',
      func: readCurrentTranscript,
      args: [videoId, trackIndex],
    });
    const current = await chrome.tabs.get(tabId);
    if (!current.url || parseSupportedUrl(current.url)?.videoId !== videoId) {
      return { ok: false, reason: 'VIDEO_CHANGED' };
    }
    const outcome: unknown = results.find((entry) => entry.frameId === 0)?.result;
    return isTranscriptOutcome(outcome, videoId)
      ? outcome
      : { ok: false, reason: 'INVALID_RESPONSE' };
  } catch {
    return { ok: false, reason: 'FETCH_FAILED' };
  }
}
