import { useState } from 'react';
import type { TranscriptReadOutcome } from '../../content/readers/transcript';

type TranscriptData = Extract<TranscriptReadOutcome, { ok: true }>;
type TranscriptError = Extract<TranscriptReadOutcome, { ok: false }>['reason'];

const ERROR_TEXT: Record<TranscriptError, string> = {
  VIDEO_CHANGED: 'The current video changed. Reload its metadata and try again.',
  NO_CAPTIONS: 'No caption track is available for this video on the current page.',
  FETCH_FAILED: 'The transcript could not be loaded from this video.',
  INVALID_RESPONSE: 'YouTube returned a transcript format we could not read.',
  TOO_LARGE: 'This transcript is too large to display in the popup.',
};

function timestamp(startMs: number): string {
  const seconds = Math.floor(startMs / 1000);
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const remaining = String(seconds % 60).padStart(2, '0');
  return hours > 0
    ? `${hours}:${String(minutes).padStart(2, '0')}:${remaining}`
    : `${minutes}:${remaining}`;
}

export function TranscriptPanel({
  loading,
  data,
  error,
  onLoad,
  onCopyDirect,
  onCopy,
}: {
  loading: boolean;
  data: TranscriptData | null;
  error: TranscriptError | null;
  onLoad: (trackIndex?: number) => void;
  onCopyDirect: () => void;
  onCopy: (text: string) => void;
}) {
  const [visibleCount, setVisibleCount] = useState(150);
  const transcriptText = data?.segments.map((segment) => segment.text).join('\n') ?? '';

  return (
    <section className="transcript-panel" aria-labelledby="transcript-heading">
      <div className="transcript-heading">
        <div>
          <span className="section-eyebrow">FROM CAPTIONS</span>
          <h2 id="transcript-heading">Transcript</h2>
        </div>
        <button
          type="button"
          className="transcript-copy"
          disabled={loading || error === 'NO_CAPTIONS'}
          onClick={() => data ? onCopy(transcriptText) : onCopyDirect()}
        >
          Copy transcript
        </button>
      </div>

      {data ? (
        <>
          <div className="transcript-toolbar">
            {data.tracks.length > 1 ? (
              <label>
                <span>Language</span>
                <select
                  value={data.selectedIndex}
                  disabled={loading}
                  onChange={(event) => {
                    setVisibleCount(150);
                    onLoad(Number(event.target.value));
                  }}
                >
                  {data.tracks.map((track) => (
                    <option value={track.index} key={track.index}>
                      {track.label}{track.autoGenerated ? ' (auto)' : ''}
                    </option>
                  ))}
                </select>
              </label>
            ) : (
              <span>{data.tracks[0]?.label}{data.tracks[0]?.autoGenerated ? ' · Auto-generated' : ''}</span>
            )}
            <span>{data.segments.length} lines</span>
          </div>
          <div className="transcript-lines" role="region" aria-label="Video transcript" tabIndex={0}>
            {data.segments.slice(0, visibleCount).map((segment, index) => (
              <div className="transcript-line" key={`${segment.startMs}-${index}`}>
                <time>{timestamp(segment.startMs)}</time>
                <p>{segment.text}</p>
              </div>
            ))}
          </div>
          {data.segments.length > visibleCount ? (
            <button
              type="button"
              className="transcript-more"
              onClick={() => setVisibleCount((count) => count + 150)}
            >
              Show more lines
            </button>
          ) : null}
        </>
      ) : loading ? (
        <p className="transcript-message" role="status">Loading transcript…</p>
      ) : error ? (
        <div className="transcript-empty">
          <p>{ERROR_TEXT[error]}</p>
          <button type="button" className="transcript-link" onClick={() => onLoad()}>
            {error === 'NO_CAPTIONS' ? 'Check again' : 'Try again'}
          </button>
        </div>
      ) : (
        <div className="transcript-empty">
          <p>Read and copy the captions from this video.</p>
          <button type="button" className="transcript-link" onClick={() => onLoad()}>
            View transcript <span aria-hidden="true">→</span>
          </button>
        </div>
      )}
    </section>
  );
}
