export interface TranscriptTrack {
  index: number;
  languageCode: string;
  label: string;
  autoGenerated: boolean;
}

export interface TranscriptSegment {
  startMs: number;
  text: string;
}

export type TranscriptReadOutcome =
  | {
      ok: true;
      videoId: string;
      tracks: TranscriptTrack[];
      selectedIndex: number;
      segments: TranscriptSegment[];
    }
  | {
      ok: false;
      reason: 'VIDEO_CHANGED' | 'NO_CAPTIONS' | 'FETCH_FAILED' | 'INVALID_RESPONSE' | 'TOO_LARGE';
    };

// Chrome serializes this function into YouTube's main world. Keep it self-contained.
export async function readCurrentTranscript(
  expectedVideoId: string,
  requestedTrackIndex: number | null,
): Promise<TranscriptReadOutcome> {
  type CaptionTrack = {
    baseUrl?: unknown;
    languageCode?: unknown;
    name?: { simpleText?: unknown; runs?: Array<{ text?: unknown }> };
    kind?: unknown;
  };
  type PlayerResponse = {
    videoDetails?: { videoId?: unknown };
    captions?: {
      playerCaptionsTracklistRenderer?: {
        captionTracks?: CaptionTrack[];
        audioTracks?: Array<{ defaultCaptionTrackIndex?: unknown }>;
      };
    };
  };

  function currentVideoId(): string | null {
    const url = new URL(location.href);
    if (url.protocol !== 'https:' || !['youtube.com', 'www.youtube.com'].includes(url.hostname)) {
      return null;
    }
    if (url.pathname === '/watch') return url.searchParams.get('v');
    return url.pathname.match(/^\/shorts\/([A-Za-z0-9_-]{11})\/?$/)?.[1] ?? null;
  }

  function playerResponseFrom(element: Element | null): PlayerResponse | null {
    if (!element) return null;
    const player = element as Element & {
      getPlayerResponse?: () => unknown;
      getPlayer?: () => { getPlayerResponse?: () => unknown } | undefined;
    };
    try {
      const response = typeof player.getPlayerResponse === 'function'
        ? player.getPlayerResponse()
        : player.getPlayer?.()?.getPlayerResponse?.();
      return response && typeof response === 'object' ? response as PlayerResponse : null;
    } catch {
      return null;
    }
  }

  if (currentVideoId() !== expectedVideoId) return { ok: false, reason: 'VIDEO_CHANGED' };

  const candidates: Array<PlayerResponse | null | undefined> = [
    playerResponseFrom(document.getElementById('movie_player')),
    playerResponseFrom(document.getElementById('shorts-player')),
    ...Array.from(document.querySelectorAll('ytd-player')).map(playerResponseFrom),
    (window as unknown as { ytInitialPlayerResponse?: PlayerResponse }).ytInitialPlayerResponse,
  ];
  const matches = candidates.filter((candidate) => candidate?.videoDetails?.videoId === expectedVideoId);
  const response = matches.find((candidate) =>
    Array.isArray(candidate?.captions?.playerCaptionsTracklistRenderer?.captionTracks)
    && candidate.captions.playerCaptionsTracklistRenderer.captionTracks.length > 0,
  ) ?? matches[0];
  if (!response) return { ok: false, reason: 'VIDEO_CHANGED' };

  const captionList = response.captions?.playerCaptionsTracklistRenderer;
  const rawTracks = Array.isArray(captionList?.captionTracks) ? captionList.captionTracks : [];
  const usable = rawTracks.flatMap((track, rawIndex) => {
    if (typeof track.baseUrl !== 'string' || typeof track.languageCode !== 'string') return [];
    let url: URL;
    try {
      url = new URL(track.baseUrl);
    } catch {
      return [];
    }
    if (
      url.protocol !== 'https:' ||
      !['youtube.com', 'www.youtube.com'].includes(url.hostname) ||
      url.pathname !== '/api/timedtext' ||
      (url.searchParams.has('v') && url.searchParams.get('v') !== expectedVideoId)
    ) return [];
    const name = typeof track.name?.simpleText === 'string'
      ? track.name.simpleText
      : Array.isArray(track.name?.runs)
        ? track.name.runs.map((run) => typeof run.text === 'string' ? run.text : '').join('')
        : track.languageCode;
    return [{
      rawIndex,
      url,
      languageCode: track.languageCode.slice(0, 32),
      label: name.slice(0, 80) || track.languageCode,
      autoGenerated: track.kind === 'asr',
    }];
  }).slice(0, 40);

  if (usable.length === 0) return { ok: false, reason: 'NO_CAPTIONS' };

  const defaultRawIndex = captionList?.audioTracks?.[0]?.defaultCaptionTrackIndex;
  const browserLanguage = navigator.language.toLowerCase().split('-')[0];
  const selected = requestedTrackIndex !== null
    ? usable.find((track) => track.rawIndex === requestedTrackIndex)
    : usable.find((track) => track.rawIndex === defaultRawIndex)
      ?? usable.find((track) => track.languageCode.toLowerCase().split('-')[0] === browserLanguage)
      ?? usable.find((track) => track.languageCode.toLowerCase().split('-')[0] === 'en')
      ?? usable[0];
  if (!selected) return { ok: false, reason: 'INVALID_RESPONSE' };

  // The caption URL comes from the current page. Restrict it to the page's own
  // YouTube origin so this action cannot fetch an arbitrary destination.
  selected.url.hostname = location.hostname;
  selected.url.searchParams.set('fmt', 'json3');
  const controller = new AbortController();
  const timer = window.setTimeout(() => controller.abort(), 8_000);
  let body: string;
  try {
    const result = await fetch(selected.url.toString(), {
      credentials: 'same-origin',
      signal: controller.signal,
    });
    if (!result.ok) return { ok: false, reason: 'FETCH_FAILED' };
    const declaredLength = Number(result.headers.get('content-length'));
    if (Number.isFinite(declaredLength) && declaredLength > 5_000_000) {
      return { ok: false, reason: 'TOO_LARGE' };
    }
    body = await result.text();
  } catch {
    return { ok: false, reason: 'FETCH_FAILED' };
  } finally {
    window.clearTimeout(timer);
  }
  if (body.length > 5_000_000) return { ok: false, reason: 'TOO_LARGE' };

  let data: unknown;
  try {
    data = JSON.parse(body);
  } catch {
    return { ok: false, reason: 'INVALID_RESPONSE' };
  }
  if (!data || typeof data !== 'object' || !('events' in data) || !Array.isArray(data.events)) {
    return { ok: false, reason: 'INVALID_RESPONSE' };
  }

  const segments: TranscriptSegment[] = [];
  let totalCharacters = 0;
  for (const event of data.events) {
    if (!event || typeof event !== 'object' || !Array.isArray(event.segs)) continue;
    const startMs = event.tStartMs;
    if (!Number.isSafeInteger(startMs) || startMs < 0) continue;
    const text = event.segs
      .map((segment: { utf8?: unknown }) => typeof segment?.utf8 === 'string' ? segment.utf8 : '')
      .join('')
      .replace(/\s+/g, ' ')
      .trim();
    if (!text) continue;
    totalCharacters += text.length;
    if (totalCharacters > 1_000_000 || segments.length >= 20_000) {
      return { ok: false, reason: 'TOO_LARGE' };
    }
    const previous = segments[segments.length - 1];
    if (previous?.startMs === startMs && previous.text === text) continue;
    segments.push({ startMs, text });
  }
  if (segments.length === 0) return { ok: false, reason: 'INVALID_RESPONSE' };
  if (currentVideoId() !== expectedVideoId) return { ok: false, reason: 'VIDEO_CHANGED' };

  return {
    ok: true,
    videoId: expectedVideoId,
    tracks: usable.map((track) => ({
      index: track.rawIndex,
      languageCode: track.languageCode,
      label: track.label,
      autoGenerated: track.autoGenerated,
    })),
    selectedIndex: selected.rawIndex,
    segments,
  };
}
